spring:
  datasource:
    url: jdbc:h2:mem:phone-service-db
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /console/h2
  sql:
    init:
      mode: always
      platform: h2

