server:
  port: 9000

info:
  application:
    name: ${spring.application.name}
    description: Phone service API
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'

spring:
  application:
    name: phone-service
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 20
        one-indexed-parameters: false
        max-page-size: 2000

